version: '3'

services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    image: chainlog-ui
    container_name: chainlog-ui
    environment:
      CHECKSUM_CONTAINER_NAME: checksum
    ports:
      - "0.0.0.0:8080:80/tcp"
  checksum:
    build:
      context: .
      dockerfile: Dockerfile.checksum
    image: chainlog-checksum
    container_name: chainlog-checksum
    environment:
      PYTHONUNBUFFERED: 1s
